# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g webpack webpack-cli --save-dev
    npm install
    npx webpack
  displayName: 'npm install, run webpack'
- script: |
    npm install
  displayName: 'npm install and build'
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    cp -R ./* $(Build.ArtifactStagingSirectory)
  displayName: 'Copy files to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirecory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build Artifacts'
   